export const PersonagensIcons = [
  {
    imgUrl: "/icons/personagens/Elesis_SD.webp",
    alt: "Elesis icon",
    nome: "Elesis",
  },
  {
    imgUrl: "/icons/personagens/Lire_SD.webp",
    alt: "Lire icon",
    nome: "Lire",
  },
  {
    imgUrl: "/icons/personagens/Arme_SD.webp",
    alt: "Arme icon",
    nome: "Arme",
  },
  {
    imgUrl: "/icons/personagens/Lass_SD.webp",
    alt: "Lass icon",
    nome: "Lass",
  },
  {
    imgUrl: "/icons/personagens/Ryan_SD.webp",
    alt: "Ryan icon",
    nome: "Ryan",
  },
  {
    imgUrl: "/icons/personagens/Ronan_SD.webp",
    alt: "Ronan icon",
    nome: "Ronan",
  },
  {
    imgUrl: "/icons/personagens/Amy_SD.webp",
    alt: "Amy icon",
    nome: "Amy",
  },
  {
    imgUrl: "/icons/personagens/Jin_SD.webp",
    alt: "Jin icon",
    nome: "Jin",
  },
  {
    imgUrl: "/icons/personagens/Sieghart_SD.webp",
    alt: "Sieghart icon",
    nome: "Sieghart",
  },
  {
    imgUrl: "/icons/personagens/Mari_SD.webp",
    alt: "Mari icon",
    nome: "Mari",
  },
  {
    imgUrl: "/icons/personagens/Dio_SD.webp",
    alt: "Dio icon",
    nome: "Dio",
  },
  {
    imgUrl: "/icons/personagens/Zero_SD.webp",
    alt: "Zero icon",
    nome: "Zero",
  },
  {
    imgUrl: "/icons/personagens/Ley_SD.webp",
    alt: "Rey icon",
    nome: "Rey",
  },
  {
    imgUrl: "/icons/personagens/Rufus_SD.webp",
    alt: "Lupus icon",
    nome: "Lupus",
  },
  {
    imgUrl: "/icons/personagens/Veigas_SD.webp",
    alt: "Veigas icon",
    nome: "Veigas",
  },
  {
    imgUrl: "/icons/personagens/Rin_SD.webp",
    alt: "Lin icon",
    nome: "Lin",
  },
  {
    imgUrl: "/icons/personagens/Asin_SD.webp",
    alt: "Azin icon",
    nome: "Azin",
  },
  {
    imgUrl: "/icons/personagens/Lime_SD.webp",
    alt: "Holy icon",
    nome: "Holy",
  },
  {
    imgUrl: "/icons/personagens/Edel_SD.webp",
    alt: "Edel icon",
    nome: "Edel",
  },
  {
    imgUrl: "/icons/personagens/Uno_SD.webp",
    alt: "Uno icon",
    nome: "Uno",
  },
  {
    imgUrl: "/icons/personagens/Decanee_SD.webp",
    alt: "Decane icon",
    nome: "Decane",
  },
  {
    imgUrl: "/icons/personagens/Ai_SD.webp",
    alt: "Ai icon",
    nome: "Ai",
  },
  {
    imgUrl: "/icons/personagens/Kallia_SD.webp",
    alt: "Kallia icon",
    nome: "Kallia",
  },
]

export const PersonagensNomes = [
  "Elesis",
  "Lire",
  "Arme",
  "Lass",
  "Ryan",
  "Ronan",
  "Amy",
  "Jin",
  "Sieghart",
  "Mari",
  "Dio",
  "Zero",
  "Rey",
  "Lupus",
  "Veigas",
  "Lin",
  "Azin",
  "Holy",
  "Edel",
  "Uno",
  "Decane",
  "Ai",
  "Kallia",
]

export const DungeonsIcons = [
  {
    imgUrl: "/icons/dungeons/Fornalha_Infernal_Icon.webp",
    alt: "Fornalha Infernal icon",
    nome: "Fornalha Infernal",
  },
  {
    imgUrl: "/icons/dungeons/Altar_da_Ruina_Icon.webp",
    alt: "Altar da Ruína icon",
    nome: "Altar da Ruína",
  },
  {
    imgUrl: "/icons/dungeons/Torre_das_Ilusoes_Icon.webp",
    alt: "Torre das Ilusões icon",
    nome: "Torre das Ilusões",
  },
  {
    imgUrl: "/icons/dungeons/Covil_de_Berkas_Icon.webp",
    alt: "Covil de Berkas icon",
    nome: "Covil de Berkas",
  },
  {
    imgUrl: "/icons/dungeons/Torre_da_Extincao_Icon.webp",
    alt: "Torre da Extinção icon",
    nome: "Torre da Extinção",
  },
  {
    imgUrl: "/icons/dungeons/Terra_do_Julgamento_Icon.webp",
    alt: "Terra do Julgamento icon",
    nome: "Terra do Julgamento",
  },
  {
    imgUrl: "/icons/dungeons/Vazio_Icon.webp",
    alt: "Vazio icon",
    nome: "Vazio",
  },
  {
    imgUrl: "/icons/dungeons/Vazio_Contaminacao_Icon.webp",
    alt: "Vazio Contaminação icon",
    nome: "Vazio Contaminação",
  },
]

export const DungeonNames = [
  "Fornalha-infernal",
  "Altar-da-Ruína",
  "Torre-das-Ilusões",
  "Covil-de-Berkas",
  "Torre-da-Extinção",
  "Terra-do-Julgamento",
  "Vazio-Invasão",
  "Vazio-Contaminação",
  "Claustro-Infinito",
]

export const Items = [
  { abrev: "moedaEpic", qtd: 0 },
  { abrev: "pedacoMoedaEpic", qtd: 0 },
  { abrev: "nucleoVulcanus", qtd: 0 },
  { abrev: "nucleoNemophi", qtd: 0 },
  { abrev: "nucleoGrandiel", qtd: 0 },
  { abrev: "simbTerraJulga", qtd: 0 },
  { abrev: "peroPrecHeroi", qtd: 0 },
  { abrev: "fragAnelHark", qtd: 0 },
  { abrev: "fragBrincoHark", qtd: 0 },
  { abrev: "fragVisuChase", qtd: 0 },
  { abrev: "fragPortal", qtd: 0 },
  { abrev: "tickDesafioEpic", qtd: 0 },
  { abrev: "tickOutroMundo", qtd: 0 },
  { abrev: "tickEvento", qtd: 0 },
  { abrev: "tickRaid", qtd: 0 },
  { abrev: "propGp", qtd: 0 },
  { abrev: "propUnica", qtd: 0 },
  { abrev: "altAtrib", qtd: 0 },
  { abrev: "redAtrib", qtd: 0 },
  { abrev: "fort16", qtd: 0 },
  { abrev: "fort17", qtd: 0 },
]

export const ItemsNames = [
  "Moeda Épica",
  "Pdç Moeda Épica",
  "Núcleo Vulcanus",
  "Núcleo Nemophilla",
  "Núcleo Grandiel",
  "Simb. T. Julgamento",
  "Pér. Prec. do Herói",
  "Frag. Anel Harkyon",
  "Frag. Brinco Harkyon",
  "Frag. Visual Chase",
  "Frag. Portal",
  "Tck. Desafio Épico",
  "Tck. Outro Mundo",
  "Tck. Evento",
  "Tck. Raid",
  "Perg. Prop GP",
  "Perg. Prop Única",
  "Perg. Alt. Atrib.",
  "Perg. Red. Atrib.",
  "Perg. Fort. +16",
  "Perg. Fort. +17",
]
